-- Log keystrokes to ~/.local/state/nvim/keylog/YYYY-MM-DD.log.
-- Claude Code's /vim-coach reads these logs to analyze editing habits and
-- give concrete advice for getting better at vim (home/.claude/skills/vim-coach).
--
-- Privacy:
--   - characters typed in insert / replace / terminal mode are masked as ·
--     by default (special keys like <Esc> <BS> <CR> are kept as-is)
--   - cmdline mode is not masked so :command habits stay visible
--   - :Keylog toggles recording (e.g. while typing passwords)
local M = {}

local defaults = {
  dir = vim.fn.stdpath("state") .. "/keylog",
  keep_days = 30, -- daily logs older than this are deleted on startup
  mask_typed_text = true, -- mask characters typed in insert/replace/terminal mode
  flush_every = 100, -- write out to the file every N buffered keys
  gap_seconds = 2, -- start a new line after a pause longer than this
  max_group = 200, -- max keys per line
}

local config = defaults
local enabled = false
local buffer = {} -- lines waiting to be written out
local group = nil -- ongoing key run { time, mode, keys, last }
local pending = 0

local function logfile()
  return config.dir .. "/" .. os.date("%Y-%m-%d") .. ".log"
end

local function close_group()
  if group and #group.keys > 0 then
    buffer[#buffer + 1] = ("%s [%s] %s"):format(group.time, group.mode, table.concat(group.keys))
  end
  group = nil
end

-- Also called from a luv timer, so vim.api / vim.fn must not be used here
local function flush()
  close_group()
  if #buffer == 0 then
    return
  end
  local f = io.open(logfile(), "a")
  if f then
    f:write(table.concat(buffer, "\n"), "\n")
    f:close()
  end
  buffer = {}
  pending = 0
end

local function record(keystr, mode, now)
  if
    not group
    or group.mode ~= mode
    or now - group.last > config.gap_seconds
    or #group.keys >= config.max_group
  then
    close_group()
    group = { time = os.date("%H:%M:%S", now), mode = mode, keys = {}, last = now }
  end
  group.keys[#group.keys + 1] = keystr
  group.last = now
  pending = pending + 1
  if pending >= config.flush_every then
    flush()
  end
end

-- Pseudo-keys that carry no signal for habit analysis
local NOISE = { "Mouse", "Scroll", "Drag", "Release", "CursorHold", "Ignore", "FocusGained", "FocusLost" }

local function on_key(typed)
  -- Empty typed = keys generated by mapping expansion etc.; capture physical input only
  if not enabled or typed == nil or typed == "" then
    return
  end
  local ok, keystr = pcall(vim.fn.keytrans, typed)
  if not ok or keystr == "" then
    return
  end
  for _, pat in ipairs(NOISE) do
    if keystr:find(pat, 1, true) then
      return
    end
  end
  -- Render control chars in mode ("\22" for <C-v> etc.) as ^V notation
  local mode = vim.api.nvim_get_mode().mode:gsub("%c", function(c)
    return "^" .. string.char(string.byte(c) + 64)
  end)
  local m = mode:sub(1, 1)
  if
    config.mask_typed_text
    and (m == "i" or m == "R" or m == "t")
    and (keystr == "<lt>" or not keystr:match("^<"))
  then
    keystr = "·"
  end
  record(keystr, mode, os.time())
end

local function prune()
  -- Filenames are YYYY-MM-DD, so string comparison doubles as date comparison
  local cutoff = os.date("%Y-%m-%d", os.time() - config.keep_days * 86400)
  for _, path in ipairs(vim.fn.glob(config.dir .. "/*.log", true, true)) do
    if vim.fn.fnamemodify(path, ":t:r") < cutoff then
      os.remove(path)
    end
  end
end

function M.setup(opts)
  config = vim.tbl_extend("force", defaults, opts or {})
  vim.fn.mkdir(config.dir, "p")
  prune()
  enabled = true

  vim.on_key(function(_, typed)
    -- Guard so an error can't unregister on_key; return nothing (don't consume keys)
    pcall(on_key, typed)
  end, vim.api.nvim_create_namespace("config.keylog"))

  local aug = vim.api.nvim_create_augroup("keylog", { clear = true })
  vim.api.nvim_create_autocmd({ "VimLeavePre", "VimSuspend", "FocusLost" }, {
    group = aug,
    callback = function()
      flush()
    end,
  })
  -- Fallback for environments where FocusLost never fires (tmux with focus-events off etc.)
  local timer = assert(vim.uv.new_timer())
  timer:start(60000, 60000, flush)

  vim.api.nvim_create_user_command("Keylog", function()
    enabled = not enabled
    if not enabled then
      flush()
    end
    vim.notify("keylog: " .. (enabled and "on" or "off"))
  end, { desc = "Toggle keystroke logging (turn off for sensitive input)" })
end

return M
